server:
  port: 8082
  context-path: /girl
girl:
  cupSize: C
  age: 18
  content: "cupSize:${girl.cupSize},age:${girl.age}}"
spring:
  datasource:
    url: jdbc:mysql://192.168.1.189:3306/dbgirl
    username: hwx
    password: hwx
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true